# -*- coding: utf-8 -*-
"""findamino.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eixGR0pEeqHue813VP64Bxi1mlAzAf-z
"""

import tkinter as tk # ส่วนนี้คือการนำ tkinter เข้ามา และเปลี่ยนเป็น tk 

def findaminoacid(): #สร้างฟังชันขึ้นมา เพื่อเรียกใช้
    aminoacid = ''#ตัวแปรที่ไว้รับค่า
    tRNA = ""#ตัวแปรที่ไว้รับค่า
    mRNA = ""#ตัวแปรที่ไว้รับค่า
    PmRNA = ""#ตัวแปรที่ไว้รับค่า
    print("Ex. att ugg gut")
    print("!!ถ้าต้องการเพิ่มค่าอีกครั้งกด space bar 1 ครั้ง!!")
    DNA = input() #รับค่าจาก window_entry มาเก็บที่ DNA
    DNA = DNA.upper() #ทำให้เป็นตัวพิมพ์ใหญ่
    print(DNA)
    # while True:
        # print("                                                                            !!ถ้าต้องการเพิ่มค่าอีกครั้งกด space bar 1 ครั้ง!!")
    # if DNA == " ":
    PmRNA+=DNA #add ค่าเข้าไปใน PmRNA
    PmRNA = list(PmRNA) #เปลียนเป็น type list เพื่อที่จะแปลงค่าทีละตัว
    print(PmRNA)
    for base in range(len(PmRNA)): #เริ่มแปลงค่าทีละตัวเพื่อหา mRNA แปลงตามข้างล่าง
        if PmRNA[base] == "A":
            PmRNA[base] = "U"
        elif PmRNA[base] == "U" or PmRNA[base] == "T":
            PmRNA[base] = "A"
        elif PmRNA[base] == "C":
            PmRNA[base] = "G"
        elif PmRNA[base] == "G":
            PmRNA[base] = "C"
    for link in PmRNA: #ใช้ for loop เพื่อนำค่ามาเก็บใน link
        mRNA+=link #เพิ่มค่าเข้าไปใน mRNA
    mRNA = mRNA.split(" ") #ใช้ split() ในการเปลงค่ากลับเป็น list
    print("codon ของ mRNA :",mRNA)
    for base in range(len(PmRNA)): #เริ่มแปลงค่าทีละตัวเพื่อหา tRNA แปลงตามข้างล่าง
        if PmRNA[base] == "A":
            PmRNA[base] = "U"
        elif PmRNA[base] == "U" or PmRNA[base] == "T":
            PmRNA[base] = "A"
        elif PmRNA[base] == "C":
            PmRNA[base] = "G"
        elif PmRNA[base] == "G":
            PmRNA[base] = "C"
    for link in PmRNA: #ใช้ for loop เพื่อนำค่ามาเก็บใน link
        tRNA+=link #เพิ่มค่าเข้าไปใน tRNA
    tRNA = tRNA.split(" ") #ใช้ split() ในการเปลงค่ากลับเป็น list
    print("codon ของ tRNA",tRNA)
    for codon in range(len(tRNA)): #ตรวจเช็คเพื่อกำหนดค่า aminoacid
        if tRNA[codon] == 'AUG':
            tRNA[codon] = "เมไทโอนีน(Met)"
        elif tRNA[codon] == "UUU" or tRNA[codon] == "UUC":
            tRNA[codon] = "ฟีนิลอะลานีน(Phe)"
        elif tRNA[codon] == 'UUA' or tRNA[codon] == "UUG" or tRNA[codon] == "CUU" or tRNA[codon] == "CUC" or tRNA[codon] == "CUA" or tRNA[codon] == "CUG":
            tRNA[codon] = "ลิวซีน(Leu)"
        elif tRNA[codon] == "AUU" or tRNA[codon] == "AUC" or tRNA[codon] == "AUA":
            tRNA[codon] = "ไอโซลิวซีน(Ile)"
        elif tRNA[codon] == "GUU" or tRNA[codon] == "GUC" or tRNA[codon] == "GUA" or tRNA[codon] == "GUG":
            tRNA[codon] = "วาลีนๅ(Val)"
        elif tRNA[codon] == "UCU" or tRNA[codon] == "UCC" or tRNA[codon] == "UCA" or tRNA[codon] == "UCG" or tRNA[codon] == "AGU" or tRNA[codon] == "AGC":
            tRNA[codon] = "ซีรีน(Ser)"
        elif tRNA[codon] == "CUU" or tRNA[codon] == "CCC" or tRNA[codon] == "CCA" or tRNA[codon] == "CCG":
            tRNA[codon] = "โพรลีน(Pro)"
        elif tRNA[codon] == "ACU" or tRNA[codon] == "ACC" or tRNA[codon] == "ACA" or tRNA[codon] == "ACG":
            tRNA[codon] = "ทรีโอนีน(Thr)"
        elif tRNA[codon] == "GCU" or tRNA[codon] == "GCC" or tRNA[codon] == "GCA" or tRNA[codon] == "GCG":
            tRNA[codon] = "อะลานีน(Ala)"
        elif tRNA[codon] == "UAU" or tRNA[codon] == "UAC":
            tRNA[codon] = "ไทโรซีน(Tyr)"
        elif tRNA[codon] == "CAU" or tRNA[codon] == "CAC":
            tRNA[codon] = "ฮิสทิดีน(His)"
        elif tRNA[codon] == "CAA" or tRNA[codon] == "CAG":
            tRNA[codon] = "กลูตามีน(Gln)"
        elif tRNA[codon] == "AAU" or tRNA[codon] == "AAC":
            tRNA[codon] = "แอสพาราจีน(Asn)"
        elif tRNA[codon] == "AAA" or tRNA[codon] == "AAG":
            tRNA[codon] = "ไลซีน(Lys)"
        elif tRNA[codon] == "GAU" or tRNA[codon] == "GAC":
            tRNA[codon] = "กรดแอสพาร์ติก(Asp))"
        elif tRNA[codon] == "GAA" or tRNA[codon] == "GAG":
            tRNA[codon] = "กรดกลูตามิก(Glu)"
        elif tRNA[codon] == "UGU" or tRNA[codon] == "UGC":
            tRNA[codon] = "ซิสเทอีน(Cys)"
        elif tRNA[codon] == "UGG":
            tRNA[codon] = "ทริปโตเฟน(Trp)"
        elif tRNA[codon] == "CGU" or tRNA[codon] == "CGC" or tRNA[codon] == "CGA" or tRNA[codon] == "CGG" or tRNA[codon] == "AGA" or tRNA[codon] == "AGG":
            tRNA[codon] = "อาร์ตินีน(Arg)"
        elif tRNA[codon] == "GGU" or tRNA[codon] == "GGC" or tRNA[codon] == "GGA" or tRNA[codon] == "GGG":
            tRNA[codon] = "ไกลซีน(Gly)"
        elif (tRNA[codon] == "UAA" or tRNA[codon] == "UAG" or tRNA[codon] == "UGA"):
            tRNA[codon] = "stop"
    for acid in tRNA: #ใช้ for loop เพื่อนำค่ามาเก็บใน link
        aminoacid = aminoacid+""+acid #เพิ่มค่าเข้าไปใน aminoacid
    aminoacid = aminoacid.split(" ") #ใช้ split() ในการเปลงค่ากลับเป็น list
    print(aminoacid)




findaminoacid()